name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  deploy:
    name: deploy-gcf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up gcloud Cloud SDK environment
        # You may pin to the exact commit or the version.
        # uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }} # optional
          project_id: ${{ secrets.PROJECT_ID }} # optional
          export_default_credentials: true # optional
      - name: GCP Config Setup
        run: gcloud config set project ${{ secrets.PROJECT_ID }}
      - name: Deploy to GCF
        run: |
          gcloud functions deploy verigood-ai-installer \
            --runtime nodejs18 \
            --allow-unauthenticated \
            --trigger-http \
            --entry-point probotApp \
            --region asia-south1 \
            --timeout=10s \
            --set-env-vars APP_ID="${{secrets.APP_ID}}",PRIVATE_KEY="${{secrets.PRIVATE_KEY}}",WEBHOOK_SECRET="${{secrets.WEBHOOK_SECRET}}"